name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    # Environment and permissions trusted publishing.
    environment:
      # Create this environment in the GitHub repository under Settings -> Environments
      name: pypi
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: false
      - name: Build
        run: uv build
      - name: Upload distributions as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment:
      name: pypi
      url: https://pypi.org/p/listdiff
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
      contents: read
    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
